# Generated by Django 2.1 on 2018-09-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=255)),
                ('car_color', models.CharField(max_length=255)),
                ('car_plate', models.SlugField(max_length=8)),
            ],
        ),
    ]
